# Copyright (c) 2024-2025 Progress Software Corporation and/or its subsidiaries or affiliates. All Rights Reserved.

## Append samples of your project ##
resources:
- quick-start.yaml
- minimal-production.yaml
- complete.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
